name: Testing TheGrid
favicon: null
layout_spectrum: 0.33265
typography_spectrum: 0.94764
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#383835'
    - '#000000'
    - '#555555'
    - '#757575'
    - '#666600'
  brandStrength: 1
  lightness: 0.7983159506693482
  saturation: 0.6832610710989684
  rhythmicContrast: 0.3970592611003667
purpose: []
